services:
  mongo:
    image: tshivanshu/database-asgn:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  backend:
    image: tshivanshu/backend-js:v1
    ports:
      - "3005:3005"
    depends_on:
      - mongo
    environment:
      - DB=mongodb://mongo:27017/

  frontend:
    image: tshivanshu/frontend-js:v3
    ports:
      - "3006:3006"
    depends_on:
      - backend
    environment:
      - REACT_APP_BASE_URL=http://backend:3005/api

volumes:
  mongo-data: