apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: "tshivanshu/backend:latest"
        ports:
         - containerPort: 3003

        env:
         - name: DATABASE_URL
           value: "mongodb://database-service:27017"
         - name: PORT
           value: "3003"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
